# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NEProTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'WoodPeckeriOS', :configurations => ['Debug']

# for macOS project
# pod 'WoodpeckerMacOS', :configurations => ['Debug']
  # Pods for NEProTest

end
